name: pyTorch3.9
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2022.3.29
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - cryptography=36.0.0
  - cudatoolkit=11.3.1
  - freetype=2.10.4
  - idna=3.3
  - intel-openmp=2021.4.0
  - jpeg=9d
  - libpng=1.6.37
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp=1.2.2
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl=1.1.1n
  - pillow=9.0.1
  - pip=21.2.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.12
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - requests=2.27.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.38.2
  - tk=8.6.11
  - torchvision=0.12.0
  - typing_extensions=4.1.1
  - tzdata=2022a
  - urllib3=1.26.8
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9