MODAL : "BaseModal"
SAVE_AS : "FNN_Basic_Modal"

BATCH_SIZE : 512
N_WORKERS : 0

FFNN_OUT : 15 #ََ  ً  ُ  ٌ  ِ  ٍ  ْ  ّ  َّ  ًّ  ُّ  ٌّ  ِّ  ٍّ  + no-diacritic = 15
FFNN_IN : 100 

lR : 0.01
EPOCHS : 300 

IS_CHECKPOINT_EXIST: false # is your data prepared for FFNN models?

TRAIN_CHECK_POINT: "Train"
VALID_CHECK_POINT: "Valid"
TEST_CHECK_POINT: "Test"